apiVersion: apps/v1
kind: Deployment
metadata:
  name: docs-service
  labels:
    app: docs-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docs-service
  template:
    metadata:
      labels:
        app: docs-service
    spec:
      containers:
        - name: docs-service
          # The image tag will be updated dynamically by ArgoCD later
          image: 012549289252.dkr.ecr.us-east-1.amazonaws.com/aerolink-docs-service-dev:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: docs-service
spec:
  selector:
    app: docs-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
